#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title AIN
graph_vlabel value
ain0.label AIN.0
ain1.label AIN.1
graph_args -l 0 --base 1000 --upper-limit 1024
graph_scale no
graph_category GPIO
EOM
        exit 0;;
esac

printf "ain0.value "
/usr/local/bin/gpio aread 0
printf "ain1.value "
/usr/local/bin/gpio aread 1
