#!/usr/bin/python
 
import spidev
import time
import os
from subprocess import check_output,call
import sys

gpio="/usr/local/bin/gpio"

# Function to read SPI data from MCP3008 chip
# Channel must be an integer 0-7
def ReadChannel(channel,trans):
  check_output([gpio, "mode", trans,"out"])
  check_output([gpio, "write", trans,"1"])
  time.sleep(0.1)
  adc = spi.xfer2([1,(8+channel)<<4,0])
  data = ((adc[1]&3) << 8) + adc[2]
  check_output([gpio, "write", trans,"0"])
  return data


if len(sys.argv) == 2 and sys.argv[1] == "config":
  print """
graph_title Moisture Sensors
graph_vlabel value
moi04.label Sensor #4-#0
graph_args -l 0 --base 1000
graph_scale no
graph_category GPIO
"""
else:
  # Open SPI bus
  spi = spidev.SpiDev()
  spi.open(0,0)
  # Define sensor channels
  sensor0 = 0
  sensor0trans = "4"
  sensor0value = ReadChannel(sensor0,sensor0trans)
  print "moi04.value %d" % (sensor0value,)
