#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Decision tree
graph_vlabel to water
dec1.label Random Forest
dec1.draw AREA
graph_args -l 0 --base 1000
graph_scale no
graph_category GPIO
EOM
        exit 0;;
esac

printf "dec1.value "
echo $(cd /home/odroid/tinkering/ && Rscript /home/odroid/tinkering/autowater/rscript.R 2>/dev/null | grep "decicion:" | perl -ne 'm/decicion:\s+([01])/; print $1')

