#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Decision tree
graph_vlabel to water
dec1.label Random Forest
dec2.label Neural Net
real.label reality
graph_args -l 0 --base 1000
graph_scale no
graph_category GPIO
EOM
        exit 0;;
esac

printf "dec1.value "
echo $(Rscript /home/odroid/tinkering/autowater/rscript.R 2>/dev/null| grep "decicion:" | perl -ne 'm/decicion:\s+(\d+\.?\d*)/; print $1')
printf "dec2.value "
echo $(Rscript /home/odroid/tinkering/autowater/rscript.R 2>/dev/null| grep "neural:" | perl -ne 'm/neural:\s+(\d+\.?\d*)/; print $1')
printf "real.value "
echo $(Rscript /home/odroid/tinkering/autowater/rscript.R 2>/dev/null| grep "real:" | perl -ne 'm/real:\s+(\d+)/; print $1')

